package layout

import (
	"strconv"
	"strings"
)

// tableRows reads the rows out of the HTML table that every one of the three
// tools returns a table as.
//
// Hand written rather than done with a parser, because of what this has to
// read. The HTML is generated by a table recognition model, it is a handful
// of tags deep, and it is frequently not well formed: an unclosed <td>, a
// <tr> that never closes, a stray <br>. A strict parser refuses the lot and
// the paper loses its results table; this reads what is there and gives up
// at the first thing it cannot make sense of, which costs at worst one row.
//
// It also means no dependency, which for a module whose whole claim is that
// it shells out rather than pulling in is worth a hundred lines.
func tableRows(s string) [][]string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	var rows [][]string
	for _, tr := range elements(s, "tr") {
		// Header and data cells in the order they are written, because a row
		// that starts with a <th> row label and carries on in <td> is the
		// commonest shape there is and reordering it moves the label.
		cells := elements(tr.body, "th", "td")
		if len(cells) == 0 {
			continue
		}
		var row []string
		for _, c := range cells {
			text := cellText(c.body)
			// A cell spanning columns is repeated across them. A Markdown
			// table has no colspan, and a blank where a heading should be
			// reads as a column nobody named.
			for i := 0; i < c.span("colspan"); i++ {
				row = append(row, text)
			}
		}
		rows = append(rows, row)
	}
	return rows
}

// An element is one tag: what was inside its angle brackets after the name,
// and what was between it and its closing tag.
type element struct {
	attrs string
	body  string
}

// span reads a colspan or a rowspan off the attributes. Anything missing or
// unparseable is one, and anything absurd is one, because a table with a
// colspan of nine thousand is a model that misread a border.
func (e element) span(name string) int {
	lower := strings.ToLower(e.attrs)
	i := strings.Index(lower, name+"=")
	if i < 0 {
		return 1
	}
	rest := strings.TrimLeft(e.attrs[i+len(name)+1:], `"' `)
	end := 0
	for end < len(rest) && rest[end] >= '0' && rest[end] <= '9' {
		end++
	}
	n, err := strconv.Atoi(rest[:end])
	if err != nil || n < 1 || n > 32 {
		return 1
	}
	return n
}

// elements finds every one of the named tags in s, in document order. A tag
// that never closes runs to the start of the next tag of any of the names,
// or to the end of the string.
func elements(s string, tags ...string) []element {
	var out []element
	lower := strings.ToLower(s)
	i := 0
	for {
		start, tag := nextTag(lower, tags, i)
		if start < 0 {
			return out
		}
		gt := strings.IndexByte(s[start:], '>')
		if gt < 0 {
			return out
		}
		attrs := s[start+len(tag)+1 : start+gt]
		body := start + gt + 1

		end := indexTag(lower, "</"+tag, body)
		next, _ := nextTag(lower, tags, body)
		switch {
		case end >= 0 && (next < 0 || end < next):
			out = append(out, element{attrs: attrs, body: s[body:end]})
			i = end + len(tag) + 2
		case next >= 0:
			out = append(out, element{attrs: attrs, body: s[body:next]})
			i = next
		default:
			return append(out, element{attrs: attrs, body: s[body:]})
		}
	}
}

// nextTag is the earliest opening tag of any of the names, at or after from.
func nextTag(lower string, tags []string, from int) (at int, tag string) {
	at = -1
	for _, t := range tags {
		i := indexTag(lower, "<"+t, from)
		if i >= 0 && (at < 0 || i < at) {
			at, tag = i, t
		}
	}
	return at, tag
}

// indexTag finds "<td" but not "<tdata", by requiring what follows the name
// to end the tag or start an attribute.
func indexTag(lower, tag string, from int) int {
	for i := from; i < len(lower); {
		j := strings.Index(lower[i:], tag)
		if j < 0 {
			return -1
		}
		at := i + j
		after := at + len(tag)
		if after >= len(lower) {
			return -1
		}
		switch lower[after] {
		case '>', ' ', '\t', '\n', '\r', '/':
			return at
		}
		i = after
	}
	return -1
}

// cellText is a cell with its markup taken out and its entities resolved.
//
// A <br> becomes a space rather than nothing, because "3.1<br>0.2" is two
// numbers and "3.10.2" is one wrong one.
func cellText(s string) string {
	s = strings.NewReplacer("<br>", " ", "<br/>", " ", "<br />", " ").Replace(s)
	return collapse(stripTags(s))
}
